import { StudentData } from '@/types';

// 模拟学生数据
export const mockStudentData: StudentData[] = [
  {
    id: '1',
    name: '张三',
    studentId: '2021001',
    grade: 'A',
    major: '计算机科学',
    email: 'zhangsan@example.com',
    phone: '13800138001',
    address: '北京市朝阳区',
    enrollmentYear: 2021,
    gpa: 3.8,
    status: 'active',
  },
  {
    id: '2',
    name: '李四',
    studentId: '2021002',
    grade: 'B+',
    major: '软件工程',
    email: 'lisi@example.com',
    phone: '13800138002',
    address: '上海市浦东新区',
    enrollmentYear: 2021,
    gpa: 3.6,
    status: 'active',
  },
  {
    id: '3',
    name: '王五',
    studentId: '2020001',
    grade: 'A-',
    major: '数据科学',
    email: 'wangwu@example.com',
    phone: '13800138003',
    address: '广州市天河区',
    enrollmentYear: 2020,
    gpa: 3.7,
    status: 'graduated',
  },
  {
    id: '4',
    name: '赵六',
    studentId: '2022001',
    grade: 'B',
    major: '人工智能',
    email: 'zhaoliu@example.com',
    phone: '13800138004',
    address: '深圳市南山区',
    enrollmentYear: 2022,
    gpa: 3.5,
    status: 'active',
  },
  {
    id: '5',
    name: '孙七',
    studentId: '2021003',
    grade: 'A+',
    major: '计算机科学',
    email: 'sunqi@example.com',
    phone: '13800138005',
    address: '杭州市西湖区',
    enrollmentYear: 2021,
    gpa: 3.9,
    status: 'active',
  },
  {
    id: '6',
    name: '周八',
    studentId: '2020002',
    grade: 'C+',
    major: '软件工程',
    email: 'zhouba@example.com',
    phone: '13800138006',
    address: '成都市锦江区',
    enrollmentYear: 2020,
    gpa: 2.8,
    status: 'suspended',
  },
  {
    id: '7',
    name: '吴九',
    studentId: '2022002',
    grade: 'B+',
    major: '数据科学',
    email: 'wujiu@example.com',
    phone: '13800138007',
    address: '武汉市洪山区',
    enrollmentYear: 2022,
    gpa: 3.6,
    status: 'active',
  },
  {
    id: '8',
    name: '郑十',
    studentId: '2021004',
    grade: 'A',
    major: '人工智能',
    email: 'zhengshi@example.com',
    phone: '13800138008',
    address: '西安市雁塔区',
    enrollmentYear: 2021,
    gpa: 3.8,
    status: 'active',
  },
];

